os:
  - linux
  - osx
language: generic
sudo: required
dist: xenial
osx_image: xcode10.2

addons:
  hosts:
    - aws-sdk-swift-test-bucket.localhost
  apt:
    packages:
    - libicu-dev
    - uuid-dev
    - pkg-config
    - libssl-dev

install:
  - source scripts/install-swift.sh
  - if [ "${OS}" != "macos" ]; then docker run -d -p 8000:8000 tray/dynamodb-local -inMemory -port 8000; fi
  - if [ "${OS}" != "macos" ]; then docker run -d -p 4569:4569 lphoward/fake-s3; fi

script:
  - source scripts/install-swift.sh
  - source scripts/help-travis-wait.sh& travis_wait 60
  - if [ "${OS}" != "macos" ]; then swift test; else swift build; fi
