name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * *'
      
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['nightly-bionic', 'nightly-focal', 'nightly-centos8', 'nightly-amazonlinux2']
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: 'apigateway,dynamodb,iam,s3,sns,sqs,ssm,sts'
        options: >-
          --health-cmd "awslocal s3 ls"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --workdir /opt/code/localstack/
    container:
      image: swiftlang/swift:${{ matrix.tag }}
      env:
        APIGATEWAY_ENDPOINT : "http://localstack:4567"
        DYNAMODB_ENDPOINT   : "http://localstack:4569"
        S3_ENDPOINT         : "http://localstack:4572"
        SNS_ENDPOINT        : "http://localstack:4575"
        SQS_ENDPOINT        : "http://localstack:4576"
        SSM_ENDPOINT        : "http://localstack:4583"
        IAM_ENDPOINT        : "http://localstack:4593"
        STS_ENDPOINT        : "http://localstack:4592"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.tag == 'nightly-bionic' || matrix.tag == 'nightly-focal'}}
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Install dependencies (Amazon Linux2/CentOS8)
      if: ${{ matrix.tag == 'nightly-amazonlinux2' || matrix.tag == 'nightly-centos8'}}
      run: |
        yum -y update
        yum -y install zlib-devel
    - name: Test
      run: swift test
