name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DISABLE_LOCALSTACK : "true"
  AWS_ENABLE_LOGGING : "true"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['nightly-bionic', 'nightly-focal', 'nightly-centos8', 'nightly-amazonlinux2']
    container:
      image: swiftlang/swift:${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.tag == 'nightly-bionic' || matrix.tag == 'nightly-focal'}}
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Install dependencies (Amazon Linux2/CentOS8)
      if: ${{ matrix.tag == 'nightly-amazonlinux2' || matrix.tag == 'nightly-centos8'}}
      run: |
        yum -y install zlib-devel
    - name: Test Resource Prefix
      # set AWS_TEST_RESOURCE_PREFIX environment variable to a random series of 8 letters
      run: |
        echo AWS_TEST_RESOURCE_PREFIX=$(cat /dev/urandom | tr -dc 'a-z' | head -c 8) >> $GITHUB_ENV
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
